### PR TITLE
Adds an SSL check from the ssllabs.com API

### PR DESCRIPTION
**Pull request by pilbot**
This check uses the service at https://www.ssllabs.com/ssltest/ and checks that the reported grade is at the specified level.

(Mirrors https://github.com/sensu/sensu-community-plugins/pull/1065 and adds the check to the ssl plugins project)

### CODE REVIEW

**Comment by maraca** [comment]
That would be a pretty awesome patch.

**Comment by mattyjones** [comment]
@pilbot 

Can you do a rebase if you ahve time so we can look at merging this.

Thanks!

**Comment by mattyjones** [comment]
@pilbot  Can you update the CHANGELOG and then I will merge this.

Thanks !

**Comment by maraca** [comment]
:+1: thanks a lot folks!

**Comment by mattyjones** [comment]
@maraca  It is also built in 0.0.3 gem

**Pull request merged**
