### PR TITLE
Loosen dependency on sensu-plugin from `~> 1.2` to `>= 1.2, < 3.0`

### PR DESCRIPTION
**Pull request by hartmantis**
#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

~Update README with any necessary configuration snippets~

~Binstubs are created if needed~

- [x] RuboCop passes

- [x] Existing tests pass 

#### Purpose

The 2.0 of sensu-plugin was recently released.

#### Known Compatablity Issues

The few [backwards-incompatible changes](https://github.com/sensu-plugins/sensu-plugin/blob/master/CHANGELOG.md#v200---2017-03-29) shouldn't impact this plugin at all.

### CODE REVIEW

**Comment by majormoses** [comment]
Thats the exact same thing.

**Comment by hartmantis** [comment]
It is? `~> 1.2` pins it to 1.x.y where x >= 2. It won't pull in the recently released 2.0.0 or 2.0.1 without expanding the dependency to allow it.

With the current master branch:

```
> bundle update
...
Using sensu-plugin 1.4.5 (was 2.0.1)
...
```

With this branch:

```
> bundle update
...
Using sensu-plugin 2.0.1 (was 1.4.5)
...
```

**Comment by majormoses** [comment]
http://guides.rubygems.org/patterns/#pessimistic-version-constraint
https://robots.thoughtbot.com/rubys-pessimistic-operator

`~> 1.2.0` would pin it to >= 1.2.0 `~> 1.2` means `1.2 >=, < 2.0`

**Comment by majormoses** [comment]
Also even if it did do that we are not ready to force everyone to have 2.x yet as it has breaking changes but we are going to need to do it in the somewhat near future.

**Comment by hartmantis** [comment]
Right. That's why I didn't change it to `~> 2.0`, so it wouldn't force people into using 2.x, just make it possible to use it.

**Comment by majormoses** [comment]
Unless ruby pessimistic versioning ios broken somehow in which we should open an issue against rubygems this is the exact same thing. @eheydrick can you validate I am not missing something?

**Comment by majormoses** [comment]
ah I see nevermind I was somehow seeing `1.2 >=, < 2.0`, still spanning multiple major versions seems like a bad idea to me... @cwjohnston I will defer to you as you are closer to this.

**Comment by hartmantis** [comment]
That's fair. The changes in 2.0.0 struck me as being relatively minor for a major version bump, but that's just from the perspective of how we use the plugin.

**Comment by majormoses** [comment]
I have not read through it enough but this looks like the reason for a major version bump: `Deprecated filtering methods in this library are now disabled by default.` I have no idea on the impact that this would have as I don't know when this global default changed, would need to dig more to determine the impact.

**Pull request closed without merging**
