### PR TITLE
Add check for CRL expiration

### PR DESCRIPTION
**Pull request by shoekstra**
#### General

- [X] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [X] Update README with any necessary configuration snippets

- [X] Binstubs are created if needed

- [X] RuboCop passes

- [X] Existing tests pass 

#### New Plugins

- [X] Tests

- [X] Add the plugin to the README

- [X] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose

Adds a check for expiring CRLs, either online or locally on disk.

### CODE REVIEW

**Comment by shoekstra** [comment]
I'm not sure why this is failing when run on Travis, when doing it locally all tests pass.

What needs fixing to make CI tests pass?

**Comment by eheydrick** [comment]
Looks like a timezone issue. I if I run it with `TZ=CET` the tests pass but with `TZ=UTC` (the travis default) or my local timezone the tests fail. So try adding a timezone to the Time object.

**Comment by shoekstra** [comment]
@eheydrick thanks for the pointer!  Just wasn't seeing it before you mentioned the time zone.

Good to merge now?  Thanks in advance!

**Comment by eheydrick** [comment]
It would be nice if the timezone was set within the tests so that anyone could run the tests locally.

**Comment by shoekstra** [comment]
@eheydrick fair point - I've moved the env var to the Rakefile 👍

**Comment by eheydrick** [comment]
Thanks!

**Comment by shoekstra** [comment]
Thank you! 😄

**Comment by shoekstra** [comment]
@eheydrick how can I help get this released?  Are you able to push a new tag/release?

**Comment by eheydrick** [comment]
Will cut a new release soon.

**Comment by shoekstra** [comment]
Thanks, appreciated.

**Comment by eheydrick** [comment]
1.1.0 has the new check and is live on rubygems now.

**Comment by shoekstra** [comment]
Thanks!

**Pull request merged**
